#!/bin/bash

 

echo "========script7=============="
echo "Will install FAISS"
echo "Will install LangGraph"
echo "Will install LangServe"
echo "Will install LangChain CLI"
echo "Will install LlamaIndex"
echo "Will install Open WebUI--needs ollama behind the scenes"
echo "You may call download_models.sh to download gguf models or from ollama library"
echo "==========================="
sleep 10

cd ~/

# Create venv for FAISS
python3 -m venv /home/ashok/faiss
source /home/ashok/faiss/bin/activate
pip3 install faiss-cpu


echo '#!/bin/bash'                                                      > /home/ashok/start/activate_faiss.sh
echo " "                                                                >> /home/ashok/start/activate_faiss.sh
echo "cd ~/"                                                            >> /home/ashok/start/activate_faiss.sh
echo "echo 'Activate FAISS library, as:'"                                >> /home/ashok/start/activate_faiss.sh                             
echo "echo 'source /home/ashok/start/activate_faiss.sh'"                 >> /home/ashok/start/activate_faiss.sh
echo "echo 'To deactivate issue just the command: deactivate'"           >> /home/ashok/start/activate_faiss.sh
echo "source /home/ashok/faiss/bin/activate"                             >> /home/ashok/start/activate_faiss.sh

# Install LM Studio
# sudo apt install libnss3-dev libgdk-pixbuf2.0-dev libgtk-3-dev libxss-dev
# sudo apt-get install libasound2

mkdir lms
cd lms
# Download current lm studio. Check the download link
wget -c https://installers.lmstudio.ai/linux/x64/0.3.9-3/LM-Studio-0.3.9-3-x64.AppImage
chmod +x *.AppImage
cd ~/

echo '#!/bin/bash'                                       > /home/ashok/start/start_lmstudio.sh
echo " "                                                 >> /home/ashok/start/start_lmstudio.sh
echo "cd /home/ashok/lms"                                >> /home/ashok/start/start_lmstudio.sh
echo "./LM-Studio-0.3.9-3-x64.AppImage"                  >> /home/ashok/start/start_lmstudio.sh

# Install Anything LLM
curl -fsSL https://cdn.useanything.com/latest/installer.sh | sh
echo "cd /home/ashok/AnythingLLMDesktop/anythingllm-desktop"         > /home/ashok/start/start_anythingllm.sh
echo "./anythingllm-desktop start"                  >>  /home/ashok/start/start_anythingllm.sh








 
