#!/bin/bash

 

echo "========script7=============="
echo "Will install FAISS"
echo "Will install LangGraph"
echo "Will install LangServe"
echo "Will install LangChain CLI"
echo "Will install LlamaIndex"
echo "Will install Open WebUI--needs ollama behind the scenes"
echo "You may call download_models.sh to download gguf models or from ollama library"
echo "==========================="
sleep 10

cd ~/

# Create 
python3 -m venv /home/ashok/faiss
source /home/ashok/faiss/bin/activate
pip3 install faiss-cpu

echo "echo 'Activate FAISS library, as:'"                                     > /home/ashok/start/activate_faiss.sh
echo "echo 'source /home/ashok/start/activate_faiss.sh'"         >> /home/ashok/start/activate_faiss.sh
echo "echo 'To deactivate issue just the command: deactivate'"           >> /home/ashok/start/activate_faiss.sh
echo "source /home/ashok/faiss/bin/activate"                             >> /home/ashok/start/activate_faiss.sh




# Installing FAISS library
  41  pip3 install faiss
   42  pip install faiss-cpu
   43  python -c "import faiss; print(faiss.__version__)"
python 
source /home/ashok/faiss/bin/activate
pip install faiss

ashok@master:~$ mkdir lms
ashok@master:~$ cd lms
ashok@master:~/lms$ wget -c https://installers.lmstudio.ai/linux/x64/0.3.9-3/LM-Studio-0.3.9-3-x64.AppImage
chmod +x *.AppImage
cd ~/
sudo apt install libfuse2
cd ~/
# ANything LLM
curl -fsSL https://cdn.useanything.com/latest/installer.sh | sh
/home/ashok/AnythingLLMDesktop/anythingllm-desktop
./anythingllm-desktop start
ashok@master:~$ echo "cd /home/ashok/AnythingLLMDesktop/anythingllm-desktop" > /home/ashok/start/start_anythingllm.sh
ashok@master:~$ echo "./anythingllm-desktop start" >> > /home/ashok/start/start_anythingllm.sh
bash: syntax error near unexpected token `>'
ashok@master:~$ echo "./anythingllm-desktop start" >>  /home/ashok/start/start_anythingllm.sh
ashok@master:~$ cat start/start_anythingllm.sh 
cd /home/ashok/AnythingLLMDesktop/anythingllm-desktop
./anythingllm-desktop start


echo "cd /home/ashok/lms" > /home/ashok/start/start_lmstudio.sh
echo "./LM-Studio-0.3.9-3-x64.AppImage" >> /home/ashok/start/start_lmstudio.sh
ashok@master:~$ cd st





 
