# LAst amended: 14th April, 2025

echo "========script1=============="
echo "Updates Ubuntu"
echo "Will install necessary packages"
echo "Will install postgresql & sqlite3"
echo "Will install Ollama quietly"
echo "Will install Fast Node Manager (fnm)"
echo "Will install uv for langflow install"
echo "Will install chromadb"
echo "==========================="

echo "========script2=============="
echo "Will install llama.cpp directly"
echo "Will install Node.js"
echo "==========================="

echo "========script3=============="
echo "Will install ollama docker"
echo "Will install langflow using uv (but in virtual environment)"
echo "Will install Flowise using npm (node package manager)"
echo "==========================="

echo "========script4=============="
echo "Install n8n with npx"
echo "Will install LocalAI docker"
echo "==========================="

echo "========script5=============="
echo "Downloads psql scripts"  
echo "Add vector storage capability to postgres"
echo "==========================="

echo "========script6=============="
echo "Will Install FAISS library"
echo "Will install redis-stack-server docker"
echo "==========================="

echo "========script7=============="
echo "Will install langchain"
echo "Will install LangGraph"
echo "Will install LangServe"
echo "Will install litellm proxy server"
echo "Will install Visual Studio Code Editor"
echo "Will install LangChain CLI"
echo "Will install LlamaIndex"
echo "Will install Open WebUI--needs ollama behind the scenes"
echo "Install python (3.13) virtual envion"
echo "You may call script8.sh "
echo "==========================="

echo "========script8=============="
echo "Will install n8n docker"
echo "Will install LM Studio"
echo "Will install AnythingLLM"
echo "Will install open webui docker"
echo "==========================="

echo "========script9=============="
echo "Will install Milvus vectordb docker"
echo "Qdrant vector db install docker"
echo "Will install Flowise docker"
echo "Will install langflow docker"
echo "Will install portainer docker"
echo "Will prepare start script for each"
#echo "May call script10.sh after this is finished."
echo "==========================="

echo "========script10=============="
echo "Will install llama-cpp-python"
echo "Will prepare a sample start script for it"
echo "Will install mongodb docker and mongosh shell"
echo "Will install mysql-server and mysql client"
echo "Will call no other script"
echo "==========================="

echo " "
echo "========neo4j=============="
echo "Will install neo4j community edition"
echo "==========================="



